### PR TITLE
Feature/build process

### PR DESCRIPTION
**Pull request by m0ppers**
This changes the general setup of waistline.

The platforms folder is gone. Cordova creates it during the build process.

I am still getting this warning here during build time:

```
/home/vagrant/build/com.waist.line/platforms/android/app/src/main/res/drawable-port-hdpi/screen.png: Error: The drawable "screen" in drawable-port-hdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
/home/vagrant/build/com.waist.line/platforms/android/app/src/main/res/drawable-port-ldpi/screen.png: Error: The drawable "screen" in drawable-port-ldpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
/home/vagrant/build/com.waist.line/platforms/android/app/src/main/res/drawable-port-mdpi/screen.png: Error: The drawable "screen" in drawable-port-mdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
/home/vagrant/build/com.waist.line/platforms/android/app/src/main/res/drawable-port-xhdpi/screen.png: Error: The drawable "screen" in drawable-port-xhdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
```

however it doesn't seem to be a problem? I created a gradle extra file to ignore it so it doesn't brake fdroid build.

The barcode scanner seems to work (contrary to the result I am getting from fdroid right now - they build their own barcode scanner for unknown reasons?).

However after scanning I only see a loader and nothing happens (I verified using an alert() locally that I get the data - how do you even log in cordova - lol). I am not sure what the problem is there. Maybe you have an idea? Maybe it works for you locally?

The only thing you should have to do to build it is npm install and then npm run build:android now. Once this is merged and works correctly (see the note about the infinite loader?) I will adjust the fdroid build once more and then it is hopefully fixed once and for all (haha)

### CODE REVIEW

**Comment by m0ppers** [comment]
sidenode: I already removed the package-lock.json from the .gitignore file. Once this is merged and you commit the package-lock.json everybody including the build process will then get the EXACT versions of all libraries that you used to create the version (contrary to the rather loose version requirements specified in the package.json file).

**Comment by davidhealey** [comment]
> how do you even log in cordova

I use chrome://inspect for debugging on my device. 

Is this ready to be merged now or do you have additional changes to make?

**Comment by m0ppers** [comment]
from my side this is good to go. please test it if it works for you and doesn't brake any of your workflows.

**Comment by m0ppers** [comment]
ah one second: the loading spinner is loading endlessly. do you have an idea what that could be?

**Comment by davidhealey** [comment]
> ah one second: the loading spinner is loading endlessly. do you have an idea what that could be?

The loading spinner when you first open the app or when you scan a barcode, or when you search?

**Comment by m0ppers** [comment]
when I initially scan an item. the url https://world.openfoodfacts.org/api/v0/product/4260107220015.json&tagtype_0=countries&tag_contains_0=contains&tag_0=United%20Kingdom seems to return a 404. but only on my tablet. on my desktop I can access it. will have a look. something is strange. not yet sure if related to my changes. will investigate

**Comment by m0ppers** [comment]
I removed the whitelist plugin previously because the documentation mentioned that it should not be needed anymore as cordova 10 supports it directly. readding it fixed the 404 :shrug: no idea why

so I am now happy. I clicked a bit back and forth and didn't encounter any errors.

**Comment by m0ppers** [comment]
frustrating. after rebuilding from scratch it tells me that the whitelist plugin is deprecated and that it won't add it to the project, breaking it again. have to do more investigation

**Comment by m0ppers** [comment]
ok the reason for this is also proving the point :joy:  : I apparently had some old/wrong stuff lying around in node_modules that cordova was picking up.

After removing them and rebuilding everything it is working as intended.

Please note that cordova 10.x is creating bundle files in release mode now (https://cordova.apache.org/docs/en/10.x/guide/platforms/android/#signing-an-app).

That took me a while to digest as I suddenly had an aab instead of an apk when building.

Not sure how/if that influences your normal release flow?

**Comment by davidhealey** [comment]
What's  androidx-adapter? I'm using Cordova 10.0 to build APKs

**Comment by m0ppers** [comment]
I am sorry. I don't think this is ever going to work. I cannot build it without changes with cordova 10 and even with changes I still get bugs.

The whitelist plugin is incompatible with cordova 10: https://github.com/apache/cordova-plugin-whitelist#deprecation-notice . It disallows cordova 10 explicitly here: https://github.com/apache/cordova-plugin-whitelist/blob/master/package.json#L29 

Then the camera plugin is using an old version. This is also not compatible with cordova 10: https://cordova.apache.org/announcements/2021/07/20/cordova-android-10.0.0.html . In the release notes they state that they disabled the android support library in favor of androidx but the camera plugin in 4.0 was still using the old android support stuff. This is the result: https://github.com/apache/cordova-plugin-camera/issues/733 . The androidx-adapter that I added and you mention fixes old plugins not supporting androidx. however the latest version (6.0) supports androidx directly so right now in my local version I just upgraded the plugin and it works without the adapter.

however after that the problems don't stop. When preparing to add foods to the openfoodfacts db you can upload an image. However after upload the image doesn't get displayed. I am getting an error that is described here: https://stackoverflow.com/questions/69103208/cordova-10-and-android-sdk-30-cannot-access-local-file-not-allowed-to-load-l . After trying out multiple things I was finally able to show the image but only after converting it from a file:// URI to a blob. 

On to the next problem: after trying to upload to the factsdatabase I am getting new errors:

```
index.html:1 Access to fetch at 'https://world.openfoodfacts.org/cgi/product_jqm2.pl?code=9783867623919&user_id=waistline-app&password=waistline&product_name=Testi&nutrition_data_per=100g&serving_size=100g&nutriment_energy-kcal_100g=undefined&nutriment_energy-kcal=undefined&nutriment_energy-kj_100g=undefined&nutriment_energy-kj=undefined' from origin 'https://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

this is it. I am giving up. I don't understand how this is working. there seems to be state in the platforms dir right now that does something that makes the application buildable. I don't know. I can locally build an android apk using cordova9 and using the docker workflow from the readme.

However when I click the barcodescanner icon in both of these builds nothing happens. I have added my latest changes but I am closing the PR. I don't think this is ever going to work and without being able to produce a real reproducable build I don't think the fdroid build can be fixed.

**Comment by davidhealey** [comment]
I'm using Cordova 10 here, so not sure why you're hitting these incompatibility issues, they are deprecated sure, but they still should work.

**Comment by EmilJunker** [comment]
> there seems to be state in the platforms dir right now that does something that makes the application buildable

I can confirm that when I completely deleted the platforms dir on my machine, the build failed. I don't remember the specific error message though. When I just execute `cordova clean android` (which also deletes most files from the platforms dir, but leaves some), the build still works. However, now that you mention it, the barcode scanner doesn't work in the version I built. 

It's all very weird indeed. There should be nothing in the platforms dir that is needed for a successful build. As far as I know, the platforms dir is not intended to be added to source control.

@davidhealey As a first step, could you remove the package-lock.json from the .gitignore file and commit your version to the repo? Maybe this can help us pinpoint the problem.

**Comment by davidhealey** [comment]
@EmilJunker Done

**Comment by EmilJunker** [comment]
@davidhealey
Thanks. Unfortunately, I'm still unable to build for Android without the package directory.

These are the steps I took. Can you confirm that the build works for you when you follow the same steps?

1. clone the repository to a new directory
2. delete the platforms folder
3. run `cordova platform add android`
4. run `cordova build android`

I get this output when running `cordova platform add android`:

```
Using cordova-fetch for cordova-android@^10.0.1
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.waist.line
        Name: Waistline
        Activity: MainActivity
        Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.0.1
Installing "cordova-plugin-browsersync-gen2" for android
Installing "cordova-plugin-camera" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-file" for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.

Installing "cordova-plugin-network-information" for android
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-whitelist" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 10.0.1, failed version requirement: >=4.0.0 <10.0.0
Skipping 'cordova-plugin-whitelist' for android
Installing "phonegap-plugin-barcodescanner" for android
Subproject Path: CordovaLib
Subproject Path: app
```

Note the bit about skipping the cordova-plugin-whitelist because it's incompatible with cordova-android 10.0.1. Do you get this too?

And I get the following output when running `cordova build android`:

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/opt/sdk (recommended setting)
ANDROID_HOME=/opt/sdk (DEPRECATED)
Using Android SDK: /opt/sdk
Starting a Gradle Daemon (subsequent builds will be faster)
:wrapper

BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Downloading https://services.gradle.org/distributions/gradle-7.1.1-all.zip
...................................................................................................................................................
Unzipping /root/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1-all.zip to /root/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl
Set executable permissions for: /root/.gradle/wrapper/dists/gradle-7.1.1-all/1wqbeia0d49252rmlcr6o8lbl/gradle-7.1.1/bin/gradle

Welcome to Gradle 7.1.1!

Here are the highlights of this release:
 - Faster incremental Java compilation
 - Easier source set configuration in the Kotlin DSL

For more details see https://docs.gradle.org/7.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Script '/waistline/app/platforms/android/CordovaLib/cordova.gradle' line: 75

* What went wrong:
A problem occurred evaluating script.
> No usable Android build tools found. Highest 30.x installed version is 24.0.3; minimum version required is 30.0.3.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 30s
Command failed with exit code 1: /waistline/app/platforms/android/gradlew cdvBuildDebug -b /waistline/app/platforms/android/build.gradle
```

#

What output do you get when you run `cordova requirements` on your machine? This is the output I get using the Docker setup:

```
Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: not installed
Please install the Android SDK Platform "platforms;android-30"
Gradle: installed /opt/gradle-4.4.1/bin/gradle

Requirements check results for browser:
Some of requirements check failed
```

It looks like the Dockerfile specifies a relatively old Android SDK and Gradle version. This could be the reason it's not working for me.

**Comment by davidhealey** [comment]
Following the steps you mentioned I hit the same failed build and exit code.

I also got this error `Unrecognized option: --illegal-access=permit` and had to remove that option from the gradlew file in order to get the build to start. 

This is what I get from cordova requirments
```
Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: not installed 
Please install the Android SDK Platform "platforms;android-30"
Gradle: installed /usr/share/gradle/bin/gradle
Some of requirements check failed
```

**Comment by EmilJunker** [comment]
Well, I have no idea what is going on. But if even you can't build the app like this, I don't think we can expect the fdroid build to succeed.

**Comment by davidhealey** [comment]
But they do succeed they are not hitting the same issue as us because they are able to make an APK...

**Comment by EmilJunker** [comment]
> they are able to make an APK

I guess that's because the platforms folder is currently added to the repo and there is something in there that makes the build work. But the resulting APK is incomplete. For example, in the APK I built (with the platforms folder present), the barcode scanner doesn't open.

**Comment by davidhealey** [comment]
I'll give that a try, then I'll see how it compares to my local version that builds succesfully.

**Comment by EmilJunker** [comment]
You can also try the version in my fork on branch `android-build`: https://github.com/EmilJunker/waistline/tree/android-build

I think with the latest changes I just pushed, the build succeeds (even with the platforms folder deleted)! I don't know if the APK is feature complete though.

**Comment by davidhealey** [comment]
@EmilJunker I got it to build. Please try this and let me know if it works for you.

Clone the repo
Copy the attached file and folder into platforms/android
cd waistline
npm install
cordova clean android
cordova build android
[android.zip](https://github.com/davidhealey/waistline/files/7136338/android.zip)

**Comment by EmilJunker** [comment]
@davidhealey Yup, that works! Build was successful.

**Comment by davidhealey** [comment]
> @davidhealey Yup, that works! Build was successful.

So maybe if I push those two things to github everything will work :) I'd like to experiment and see what I can remove from the platforms folder and still build succesfully so that I don't push uneeded things.

**Comment by EmilJunker** [comment]
For me, the build works now even with the platforms folder completely deleted.

I upgraded my Docker setup to Android SKD 30 and Gradle 7.1.1. I also made a few changes to the package.json and package-lock.json (see https://github.com/EmilJunker/waistline/commits/android-build)

`cordova requirements` now outputs this:

```
Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-30
Gradle: installed /opt/gradle-7.1.1/bin/gradle
```

**Comment by davidhealey** [comment]
That's good, so I should be able to remove the platforms folder from github?

**Comment by EmilJunker** [comment]
> so I should be able to remove the platforms folder from github?

I'm not sure yet. It would certainly be desirable to be able to remove it. But it looks like the APK I was able to build is not entirely feature complete. The barcode scanner works now, but I'm having the same issue @m0ppers described in https://github.com/davidhealey/waistline/pull/332#issuecomment-915519863 where the photos are not displayed. But if I understand this correctly, the latest commit https://github.com/m0ppers/waistline/commit/aebfbe9a547f7939541322abf9e72e733aec1bad should fix that.

**Comment by EmilJunker** [comment]
I'm now pretty much at the point where @m0ppers was too. I can build the app locally (without the platforms folder present) and everything works except for the interaction with OFF where I'm getting weird CORS errors for unknown reasons.

When I try to save my OFF credentials, I get this error:
```
Access to fetch at 'https://world.openfoodfacts.org/cgi/session.pl?user_id=test&password=test' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

And when I try to upload a new food item to OFF, I get this error:
```
Access to fetch at 'https://world.openfoodfacts.org/cgi/product_jqm2.pl?code=4316268528092&user_id=waistline-app&password=waistline&product_name=Beeren-Mischung&brands=Beste%20Ernte&nutrition_data_per=100g&serving_size=750g&nutriment_energy-kcal_100g=52&nutriment_energy-kcal=52&nutriment_energy-kj_100g=217.71&nutriment_energy-kj=217.71' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

Apart from these two bugs, everything else works. I have opened a pull request anyway, see #340.

I'm positive @davidhealey or someone else will be able to fix these CORS errors. And then we should be one step closer to getting a working fdroid build too.

**Comment by davidhealey** [comment]
Are you getting CORS errors in the Android version?

**Comment by EmilJunker** [comment]
The error messages I posted are from the browser. But in the Android version I built, saving OFF credentials and uploading items to OFF doesn't work either, so I assume it's because of the CORS error.

**Comment by davidhealey** [comment]
CORS errors shouldn't occur in the Android build, only the browser one - however there should be a check to prevent off uploads being attempted in the browser (maybe I remove the safety check...). Use chrome://inspect to see if it is CORS that is causing the issue or something else.

**Comment by EmilJunker** [comment]
I tested it with chrome://inspect and both issues are caused by CORS on my phone.

**Comment by davidhealey** [comment]
Interesting, I assume it's an issue caused by the whitelist plugin (or lack of it)

**Comment by EmilJunker** [comment]
When I build the APK from the current `master` branch (where the platforms folder is present), the request works. I don't get any CORS errors. These are the request details from chrome://inspect:
```
General:
Request URL: https://world.openfoodfacts.org/cgi/session.pl?user_id=Test&password=test
Request Method: GET
Status Code: 200 
Remote Address: 213.36.253.206:443
Referrer Policy: strict-origin-when-cross-origin

Response Headers:
content-encoding: gzip
content-length: 6363
content-type: text/html; charset=UTF-8
date: Sat, 11 Sep 2021 11:39:37 GMT
expires: Fri, 10 Sep 2021 11:39:37 GMT
server: nginx/1.10.3
strict-transport-security: max-age=63072000
vary: Accept-Encoding
x-content-type-options: nosniff
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-frame-options: DENY
x-request-id: dAid1qsQv71kxdOA
x-xss-protection: 1; mode=block

Request Headers:
:authority: world.openfoodfacts.org
:method: GET
:path: /cgi/session.pl?user_id=Test&password=test
:scheme: https
accept: */*
accept-encoding: gzip, deflate
accept-language: en-DE,en;q=0.9,de-DE;q=0.8,de;q=0.7,en-US;q=0.6
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Linux; Android 10; ONEPLUS A6003 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.62 Mobile Safari/537.36
x-requested-with: com.waist.line

Query String Parameters:
user_id: Test
password: test
```

Compare that to the failed request in the APK I built from my fork branch `android-build` where the platforms folder is deleted:
```
General:
Request URL: https://world.openfoodfacts.org/cgi/session.pl?user_id=Test&password=test
Referrer Policy: strict-origin-when-cross-origin

Response Headers:
content-encoding: gzip
content-length: 6369
content-type: text/html; charset=UTF-8
date: Sat, 11 Sep 2021 11:44:40 GMT
expires: Fri, 10 Sep 2021 11:44:40 GMT
server: nginx/1.10.3
strict-transport-security: max-age=63072000
vary: Accept-Encoding
x-content-type-options: nosniff
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-frame-options: DENY
x-request-id: dWEup12eFmVhnAp5
x-xss-protection: 1; mode=block

Request Headers:
:authority: world.openfoodfacts.org
:method: GET
:path: /cgi/session.pl?user_id=Test&password=test
:scheme: https
accept: */*
accept-encoding: gzip, deflate
accept-language: en-DE,en;q=0.9,de-DE;q=0.8,de;q=0.7,en-US;q=0.6
origin: https://localhost
referer: https://localhost/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Linux; Android 10; ONEPLUS A6003 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.62 Mobile Safari/537.36
x-requested-with: com.waist.line

Query String Parameters:
user_id: Test
password: test
```

The only difference between the two seems to be the presence of `origin: https://localhost` and `referer: https://localhost/` in the request headers from my fork. Could this be the cause of the CORS error?

**Comment by davidhealey** [comment]
Yes definitely

**Comment by EmilJunker** [comment]
Well, I don't know why they're there or how to get rid of them. Any ideas?

**Comment by davidhealey** [comment]
Have you changed anything in config.xml?

**Comment by EmilJunker** [comment]
> Have you changed anything in config.xml?

No. In particular, the line `<access origin="*" />` is still there and should be respected.

**Comment by davidhealey** [comment]
I'm not sure then...

**Comment by EmilJunker** [comment]
This is getting weirder and weirder.

I changed the lines in config.xml from
```
<access origin="*" />
<allow-intent href="http://*/*" />
<allow-intent href="https://*/*" />
<allow-intent href="*" />
<allow-navigation href="*" />
```
to
```
<access origin="http://www.example.com" />
<allow-intent href="http://*/*" />
<allow-intent href="https://*/*" />
<allow-intent href="*" />
<allow-navigation href="http://www.example.org" />
```

#

In the APK built from the current `master` branch, this has the expected effect. HTTP requests to external sources get blocked. Most notably, I can no longer search for OFF items.

Executing `fetch()` from the chrome://inspect console also behaves pretty much as you would expect. I can only access `http://www.example.com` and `http://www.example.org`. For anything else I get 404.

image

#

However, in the APK built from my fork `android-build` branch, this changes nothing. I'm still able to search for OFF food items. And I still get the same CORS error when I try to save my OFF credentials.

When I execute `fetch()` from the console, most requests yield CORS errors. Only the request to the OFF search API works because that one explicitly has `access-control-allow-origin: *` in its response headers.

image

That means the access rules in config.xml are ignored for some reason.

**Comment by davidhealey** [comment]
Yes, and they're not ignored when building from my branch which is weird.

**Comment by EmilJunker** [comment]
I was finally able to fix it!

I downgraded to cordova-android 9.1 and re-added the whitelist plugin. Now it respects the access rules in config.xml. Maybe the whitelist feature that's supposedly built into cordova-android 10.x is buggy 🤷

Unfortunately, this also meant that I had to downgrade the camera plugin from version 6.0 to 5.0.3 which doesn't support the androidx libraries yet, so I also had to add that androidx-adapter thing too.

But anyway, it works now. I'm able to build a fully featured APK locally without the platforms folder present.

**Comment by EmilJunker** [comment]
Well, your package.json specifies cordova-android version 10.0.1, but multiple files in the platforms folder still reference version 9.1:

https://github.com/davidhealey/waistline/blob/40e37253eb9f3942c02b8929c3dfb31798ed6e4d/platforms/android/platform_www/cordova.js#L22

https://github.com/davidhealey/waistline/blob/40e37253eb9f3942c02b8929c3dfb31798ed6e4d/platforms/android/app/src/main/assets/www/cordova.js#L22

Maybe you were actually building with cordova-android 9.1 and just didn't realize it?

**Comment by davidhealey** [comment]
Aha interesting, any way I can check that?

**Comment by EmilJunker** [comment]
I'm not sure. Do you see any warnings among the lines `failed version requirement: >=4.0.0 <10.0.0
Skipping 'cordova-plugin-whitelist' for android` when you build? Because if you don't, chances are you're actually not using cordova-android 10.0.1.

**Comment by davidhealey** [comment]
I'll check tomorrow and let you know

**Comment by davidhealey** [comment]
This is my entire build output

```
cordova build android --release
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/home/dave/.apps/android/sdk (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: /home/dave/.apps/android/sdk
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :CordovaLib
[Cordova] cdvMinSdkVersion is overridden, try it at your own risk.

> Task :app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /media/dave/B/Projects/Cordova/waistline/platforms/android/app/src/main/java/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:lintVitalRelease
/media/dave/B/Projects/Cordova/waistline/platforms/android/app/src/main/res/drawable-port-hdpi/screen.png: Error: The drawable "screen" in drawable-port-hdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
/media/dave/B/Projects/Cordova/waistline/platforms/android/app/src/main/res/drawable-port-ldpi/screen.png: Error: The drawable "screen" in drawable-port-ldpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
/media/dave/B/Projects/Cordova/waistline/platforms/android/app/src/main/res/drawable-port-mdpi/screen.png: Error: The drawable "screen" in drawable-port-mdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
/media/dave/B/Projects/Cordova/waistline/platforms/android/app/src/main/res/drawable-port-xhdpi/screen.png: Error: The drawable "screen" in drawable-port-xhdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]

   Explanation for issues of type "MissingDefaultResource":
   If a resource is only defined in folders with qualifiers like -land or -en,
   and there is no default declaration in the base folder (layout or values
   etc), then the app will crash if that resource is accessed on a device
   where the device is in a configuration missing the given qualifier.

   As a special case, drawables do not have to be specified in the base
   folder; if there is a match in a density folder (such as drawable-mdpi)
   that image will be used and scaled. Note however that if you  only specify
   a drawable in a folder like drawable-en-hdpi, the app will crash in
   non-English locales.

   There may be scenarios where you have a resource, such as a -fr drawable,
   which is only referenced from some other resource with the same qualifiers
   (such as a -fr style), which itself has safe fallbacks. However, this still
   makes it possible for somebody to accidentally reference the drawable and
   crash, so it is safer to create a default dummy fallback in the base
   folder. Alternatively, you can suppress the issue by adding
   tools:ignore="MissingDefaultResource" on the element.

   (This scenario frequently happens with string translations, where you might
   delete code and the corresponding resources, but forget to delete a
   translation. There is a dedicated issue id for that scenario, with the id
   ExtraTranslation.)

4 errors, 0 warnings

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by EmilJunker** [comment]
Please remove the whitelist plugin with `cordova plugin rm cordova-plugin-whitelist` and then build again. If it really uses cordova-android 10.0.1, the build should still work and the resulting APK should allow to save OFF credentials.

**Comment by davidhealey** [comment]
Works here - [waistline-release.zip](https://github.com/davidhealey/waistline/files/7153819/waistline-release.zip)

**Comment by EmilJunker** [comment]
Are you sure that it works? In the APK you just uploaded, I can't search for food items on OFF. And when I save OFF credentials, I always get "login successful" even when I enter wrong passwords. This clearly isn't working right.

What does `cordova plugin list` return for you?

**Comment by davidhealey** [comment]
Ah you're right. The search doesn't worked and I assumed the login successful message was all I was looking for.

**Comment by EmilJunker** [comment]
This strongly suggest that you are still building with cordova-android 9.1 which requires the whitelist plugin to work. If it was cordova-android 10.0.1, it would work without the whitelist plugin.

So there is no reason not to merge my proposed changes from #340 then, is there?

**Comment by davidhealey** [comment]
Done :)

**Comment by EmilJunker** [comment]
Thanks. I'm not sure if this change alone will fix the fdroid build or if we also need to update the build script as discussed in #293.

**Comment by davidhealey** [comment]
Adding <preference name="AndroidInsecureFileModeEnabled" value="true" /> to config.xml seems to make it work...

**Comment by EmilJunker** [comment]
> Adding `<preference name="AndroidInsecureFileModeEnabled" value="true" />` to config.xml seems to make it work...

Yes, it works! Awesome!

I've made the necessary changes in #348. So merging that PR should finally fix it (including the camera issue described in #299).

**Comment by davidhealey** [comment]
When you build do you use zipalign? At the moment I'm getting a verification error with it that I need to solve before pushing the next release.

**Comment by EmilJunker** [comment]
> do you use zipalign

No. I don't have any experience with zipalign.

**Comment by davidhealey** [comment]
I fixed the zipalign thing. Is it still necessary for me to upload the package-lock file?

**Comment by EmilJunker** [comment]
Yes, the package-lock is meant to be added to source control, see https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by davidhealey** [comment]
Ok, I'll fix the conflicts and upload it. Then I'll merge your pull request and make a few adjustments to it - the nutrition update thing - and I think we should be good to test fdroid again...

**Pull request closed without merging**
