### PR TITLE
Use OFF nutriments for the prepared product when nutriments as sold are not available

### PR DESCRIPTION
**Pull request by EmilJunker**
I went ahead and implemented the changes proposed in #285 myself.

### CODE REVIEW

**Comment by davidhealey** [comment]
Thanks, I'll review it at the weekend

**Comment by njmdietrich** [comment]
If I may butt in, I don't think the prepared product should be the default values used. Personally, I like to weigh things out before preparing them, and I would imagine most people planning their meals by calories/nutrients (rather than just tracking them) do the same. So I think if available, nutrients as sold are preferable, perhaps with a function to choose which information to use.

**Comment by EmilJunker** [comment]
@njmdietrich I think you misunderstand the meaning of "prepared product". It only affects products that are not supposed to be eaten as sold anyway. The reason this bug hadn't been noticed by anyone until now is because the vast majority of products don't even specify nutrition info for the prepared product. It only affects things like pudding powder or dried products to be rehydrated.

If an item specifies nutrition info for the prepared product, then it makes perfect sense to use it.

**Comment by EmilJunker** [comment]
Now that I think about it, I believe some mueslis actually specify the nutrition info for both the product as sold and the prepared product (the latter including the milk). In cases like this, it would indeed be preferable to use the nutrients as sold over the ones for the prepared product.

Alright, I've now changed it so nutriments for the prepared product are only used when the nutrients as sold are not available.

**Comment by njmdietrich** [comment]
Yes, I also know some frozen foods etc have nutriments for the prepared product, i.e. when cooked, in which case it also makes sense to have the "as sold" info for weighing things out before cooking.

**Pull request merged**
