### PR TITLE
testing: add wdio/appium/jasmine tests

### PR DESCRIPTION
**Pull request by corngood**
This adds UI tests that are run on Travis CI using the android emulator.  It's inspired by:

https://medium.com/the-web-tub/testing-cordova-apps-with-appium-2b3b236e026b

I spent quite a lot of time trying to make it 100% reliable, but it still fails occasionally (maybe 5%?).  I think it's mostly because of hard-coded timeouts in various packages, and the fact that the emulator is extremely slow.  This seems to be a common complaint with the android emulator on travis.

The tests themselves are still quite simple.  It just clicks through all the top level pages in the app.  I would like to add more functionality and regression tests in the future, particularly when I find bugs.

You can also run the tests locally on any device connected to adb, but I'd suggest doing it only with an emulator or test device, because appium may install some helper apps, wipe app data, etc.

### CODE REVIEW

**Comment by davidhealey** [comment]
It says some checks haven't been completed. Should I wait for that before merging?

**Comment by corngood** [comment]
Yeah, that's the idea.  It actually failed, so I'll retry it.  If you look at the bottom of the log on:

https://travis-ci.org/corngood/waistline/builds/459233541

That's the sort of test report you should see for a passed build.

I'll run it a few more times to see how stable it is.

**Comment by davidhealey** [comment]
I just noticed all tests are passing now so I'll merge this

**Comment by corngood** [comment]
Ok, thanks.  It still may be slightly unreliable, so let me know if you see a lot of unexpected failures.

I haven't had a chance to work on waistline for a couple of weeks, but I've been still been using it every day, and it's been working great.  Maybe over the holidays I'll have a bit of time to improve testing, make a few minor fixes, etc.

**Pull request merged**
