### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by davidhealey**

### CODE REVIEW

**Comment by davidhealey** [comment]
:(

**Comment by EmilJunker** [comment]
@davidhealey It looks like there is still the issue with the two Serbian translations overwriting each other. If you give me access to the Crowdin project, I can try to fix this. I know for a fact that I was able to fix a similar problem in one of my own Crowdin projects. If I remember correctly, the Chinese translation was written to a file named `zh-CN-filename`, but I needed it to be `zh-Hans-filename` or something like that. I don't remember how exactly I did it (I only know that it took me quite some time to figure it out), but I'm positive I can do it again :)

**Comment by davidhealey** [comment]
No problem, how do I give you access?

**Comment by EmilJunker** [comment]
My Crowdin username is EmilJunker. You should be able to add me as a member somewhere in the Crowdin project settings.

**Comment by davidhealey** [comment]
Done

**Comment by EmilJunker** [comment]
I believe it's a problem that the locale file is currently added twice. I'll try to remove the older file and set up the proper language code mapping for the other one.

**Comment by EmilJunker** [comment]
Looks good now 🎉

**Pull request merged**
