### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by corngood**
- remove all cordova generated files: node_modules, platforms/, plugins/, and update .gitignore
- remove executable flag from source files
- update android platform and browsersync plugin (to fix a build error)
- add travis CI script
- add emacs .dir-locals.el to set 2-space indentation for javascript

@davidhealey 

Could you try this out when you get a chance and make sure everything still works the way you expect?  You'll need to run `cordova prepare` to repopulate the generated files.

Also, if you enable Travis CI on this repo, it should work.  If you have another preferred CI system, let me know.

### CODE REVIEW

**Comment by davidhealey** [comment]
Well something's not right

```
cordova prepare browser
Unable to load PlatformApi from platform. Error: Cannot find module '/media/dave/Work 2/Android Studio Projects/waistline/platforms/browser/cordova/Api.js'
Unhandled "error" event. (The platform "browser" does not appear to be a valid cordova platform. It is missing API.js. browser not supported.)
```

I don't have time to work this out at the moment though.

**Comment by corngood** [comment]
Did you try `cordova prepare`?  It should do both android and browser because they are both in the config.xml.

I have seen this type of error before, but cleaning the workspace and preparing always fixed it.

**Comment by corngood** [comment]
@davidhealey I'm just trying the browser build for the first time.  I did `cordova build browser`, which completed with no output, and then opened `platforms/browser/www/index.html`.  Is that the right thing to do?

The app partially works in firefox.  I could search for food items on OFF, but the add food page is pretty broken and I couldn't find a way to actually add the item (there's no checkmark button like on android).

I'm just wondering if this is how it normally works, if I built it wrong, or if I broke it with my changes.

**Comment by davidhealey** [comment]
I think something is broken but I'll need to check further. I do all my development in the browser (followed by final debugging on my Android devices).

You'll want to have the browser live refresh plugin installed (that might be something that was in the node or platforms folder I'm not quite sure), then you cd to the project folder and use this command **cordova run browser -- --live-reload**. This will start a virtual server which you can connect to in your browser (I use firefox) by going to http://localhost:8000/. Then it will run just like the app (I hit F12 and switch to responsive design mode to simulate a mobile device).

**Comment by corngood** [comment]
Ok, thanks.  I tried that method of running and it seems to work and reload files properly, at least on my system.  I'm using cordova 8.1.2 btw.

**Comment by davidhealey** [comment]
Ok, I'll give it another run later and see if it works for me. Did you do any other steps?

**Comment by corngood** [comment]
No, just `cordova prepare`, `cordova run browser -- --live-reload`.  There are still some problems with the browser version though (on mine anyway):

- missing icons for the menu button, back, accept, etc.
- import/export doesn't seem to work

**Comment by corngood** [comment]
@davidhealey do you mind enabling Travis CI for the repo?  Then we can start getting build results on PRs.

**Comment by davidhealey** [comment]
I don't mind, but I have no idea what it is or how I do it, please educate me :)

**Comment by corngood** [comment]
@davidhealey It's a free continuous integration system which integrates with github.  I think it's the most popular one by a long way.  

You just need to go to https://travis-ci.org/ and authenticate with your GH account, and then enable testing of this repo.

Then you'll get the equivalent of this, which I enabled for my fork: https://travis-ci.org/corngood/waistline.  On GH you get notifications of test status on PRs, and badges for commits like on: https://github.com/corngood/waistline/commits/timezones.

**Comment by davidhealey** [comment]
Thanks. I've enabled it now on the Repo, let me know if I need to do anything else to get it running.

**Comment by corngood** [comment]
That should be fine.  Next time you push something, or someone creates a PR, it should do builds, notify on failure, etc.

So far it's only testing that an apk can build, but it gives us somewhere to add tests e.g. js linting, automated testing.

**Comment by davidhealey** [comment]
I'm going to re-add the platforms >> android folder to the git repo because it turns out F-Droid is relying on it to create updates.

**Comment by corngood** [comment]
It doesn't sound right that it would need build artifacts in the repo, but I don't know anything about fdroid packaging.  Is it documented somewhere?  How do you configure it?

**Comment by corngood** [comment]
Actually I think I found the relevant portion of the docs:

> Special note on Cordova/Phonegap/HTML-Apps:
>
> We cannot build cordova apps directly, but recent version allows you to export the platform-specific code that can be build standalone using “gradle”. So for now we require this code to be present and up-to-date in the source repository.

That's unfortunate.

**Comment by davidhealey** [comment]
More detail here - https://github.com/davidhealey/waistline/issues/69#issuecomment-455290095 

Seems the build folders aren't needed

**Pull request merged**
