### PR TITLE
Hebrew translation

### PR DESCRIPTION
**Pull request by yarons**
I've also added a Crwodin project for that, would you like to further integrate with it and have full permissions or you would rather me deleting it? 

It's auto updated at the moment so when new translations are presented they will be added to the platfrom automatically while all the translators should get notifications about it (if this is what they've chose).
Adding a new translation currently requires some manual work but with the right configuration it can be automated.

### CODE REVIEW

**Comment by davidhealey** [comment]
This is excellent. I don't have time to check it out and merge it today as I'm going on holiday but I'll do it next week when I'm back.

I'm not familiar with Crowdin, please tell me more.

**Comment by yarons** [comment]
One of many translation platform, it allows translation collaboration and easy git integration so you can commit the changes back to git seemlessly.
I tried other platform but they didn't support Cordova JSON localization format so I sticked with this one.

The only downside I see is that this platform is not open source, as opposed to Weblate which is Open Source yet does not allow openning repositories automatically, we need to apply to manage a localization project in this platform.

Sign up and give me your username, I'll add you so you can play around.
Thank you!

**Comment by davidhealey** [comment]
Thanks, this is merged now and will be available in the next update. I don't really do much with translations, I included it at the request of others, I don't fancy signing up for something I don't plan to use but I'm happy for people to add translations through pull requests as you have done.

**Comment by yarons** [comment]
That will require some technical skills from language speakers.
Setting up Crowdin actually provides you with API to pull their translation right into your code or even better: set up an integration task to deploy the translations directly into git.

There are also more open platform such as Weblate, I can manage it for you, all I need is permission to pull translation to the project (you can even help me set it up) and you will just need to add the relevant link here so people will know how to contribute translations.

As flat as the learning curve becomes the more translations that you'll get.

I can assist with everything that you need, I have vast experience and knowledge in the field.

**Comment by davidhealey** [comment]
If you're willing to manage it all then I'm happy with that. What GitHub settings do you need me to apply?

**Comment by yarons** [comment]
Well, this is the complete guide:
https://support.crowdin.com/github-integration/

I think the best available method here is the access token, any other method will require you to use Crowdin (which is not that bad, you can be an inactive user for the project and I'll just let you know when your help is needed).

**Comment by davidhealey** [comment]
I think that will only work with a GitHub Enterprise Account?

**Comment by yarons** [comment]
LOL, that's a case for a private repository 😄.

**Comment by davidhealey** [comment]
So it will work with public too?

**Comment by yarons** [comment]
I guess it should, you want to connect there and assist me? I don't want to have a ping pong and it's only a single activation, after that, you're free to leave if you want :)

**Comment by davidhealey** [comment]
Ok I've signed up to crowdin and I've joined the Waistline project. The instructions say _open Project Settings, Integrations tab in Crowdin_ but I don't see these options...

**Comment by yarons** [comment]
First let me add you as admin, what's your username?

**Comment by davidhealey** [comment]
dhealey

**Comment by yarons** [comment]
Please try again.

**Comment by davidhealey** [comment]
Integration is greyed out for me

https://pasteboard.co/HJsUyqs.png

**Comment by davidhealey** [comment]
Never mind, I figured it out, I had to delete the existing integration and start over

**Comment by davidhealey** [comment]
I really have no idea what I'm doing with setting up the configuration paths, hopefully you can access it now and set it correctly?

**Comment by yarons** [comment]
I'm sorry, for some reason I can't edit your integration. Is there a way you can pass me the token and I'll do all the rest?

**Comment by davidhealey** [comment]
Hi, I've just emailed the access token to you

**Pull request merged**
