### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by davidhealey**

### CODE REVIEW

**Comment by EmilJunker** [comment]
It appears to me that the translation files for Serbian (Latin) and Serbian (Cyrillic) are overwriting each other because they both have the same two-letter-code "sr". I believe there is a way to set up custom language codes on the Crowdin project settings page. Doing so might fix this problem.

**Comment by davidhealey** [comment]
Thanks, I'll take a look now

**Comment by EmilJunker** [comment]
Maybe we can switch to four letter codes for all languages. But I don't know if this would have implications regarding the `getLanguage()` and `localize()` function in index.js. It's possible that they would need to be modified slightly, but it should be managable.

Alternatively, you could just change the two letter code of the Latin variant from "sr" to "sr-CS" via the language mapping feature on the Crowdin settings page.

**Comment by davidhealey** [comment]
I've setup the custom mapping. How do I know if it worked?

**Comment by EmilJunker** [comment]
I'm not sure. It's possible we need to wait a few hours for Crowdin to pick up the change and to build and push the new files. Or maybe someone first needs to edit the Serbian translation to trigger this.

**Comment by EmilJunker** [comment]
> wanted to see if there were any bug reports first

Smart thinking, but I'm afraid the latest release hasn't been picked up by F-Droid either. Their build metadata is still on version 3.4.1 for some reason: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.waist.line.yml

**Comment by davidhealey** [comment]
Oh strange, did I miss something in the config.xml?

**Comment by EmilJunker** [comment]
It looks like in the commit that was tagged for version 3.4.2, the version code in config.xml was still set to 30401:

https://github.com/davidhealey/waistline/tree/d8556def6d0b1772067682890ca07fde6eff48b0

But in the latest commit tagged for version 3.4.4, the code is correctly set to 30404:

https://github.com/davidhealey/waistline/tree/4f99f982232df41143535cb52c71a454742fca6a

So I don't know why version 3.4.4 hasn't been picked up. Maybe it's because of the large number of releases and re-releases you published in a short period of time 🤷‍♂️

**Comment by davidhealey** [comment]
> [](https://github.com/davidhealey/waistline/tree/4f99f982232df41143535cb52c71a454742fca6a)
> 
> So I don't know why version 3.4.4 hasn't been picked up. Maybe it's because of the large number of releases and re-releases you published in a short period of time

Yeah I had some issues that day :p Hopefully it will be picked up or the next release will.

**Comment by EmilJunker** [comment]
Apparently the thing with changing the language code didn't work. The latest two commits did overwrite each other again.

**Comment by davidhealey** [comment]
Ah that's annoying. Any other ideas?

**Comment by davidhealey** [comment]
I'd rather avoid doing something like that if possible just for this one use case. I'll try merging and we'll see what happens.

**Pull request merged**
