### PR TITLE
Nutrition Name Corrections - English

### PR DESCRIPTION
**Pull request by daygle**
Ensure that nutrition labels are shown with a capital letter for the first character of each word. Also updated the word 'Proteins' to 'Protein' as shown on nutrition labels.

### CODE REVIEW

**Comment by davidhealey** [comment]
I think this needs to be done through crowdin

**Comment by daygle** [comment]
> I think this needs to be done through crowdin

Really? A assumed source code was maintained here?

**Comment by davidhealey** [comment]
From the readme

image

**Comment by davidhealey** [comment]
I think the en one might not be included though. I'll need to check.

**Comment by daygle** [comment]
> I think the en one might not be included though. I'll need to check.

Thanks David

**Comment by davidhealey** [comment]
Ok from what I can tell the en is like the template file that all the others read from. So hopefully if I merge your change it won't be overwritten by Crowdin.

**Comment by daygle** [comment]
Thank you :)

**Pull request merged**
