### PR TITLE
Diary nutriments

### LINKED ISSUE #218: [Feature Request]: Subtotals for macro-nutrients in Diary
In addition to counting calories, it is very important to me to track total gr of protein, sugar, fiber, carbs, fat, etc. I have been using FatSecret since 2014 and they display a totals bar at the top and subtotals for each meal, and even for each food in a meal. Your app comes so close to FatSecret as a FOSS alternative that this feature is the only thing it needs, imho. 

**The columns at the top** are carried down the tableview rows to each meal. So the top row with the column labels 'Fiber, Sugar, Sod, Protein, Cals' show my grand totals for that day. Then below on each 'meal table-row' the subtotals for that meal are displayed in the corresponding spots of each column.
FatSecret 1-collapsed-meals

**When you expand the meal,** you see each food showing it's amounts for each nutrient in the same column order. FatSecret makes this optional, calling it the 'detailed view.'
FatSecret 2-expanded-meals

**It only lets you display 4** columns to the right of Cals, which is always present. But it lets you choose which categories to show in those 4 spots:
FatSecret 3-choose-collumns

I'm not sure if you are aware of FatSecret, but it feels like you were inspired by it, and that is why I like your app. I also am happy that you are using the OpenFoodFacts database because I have contributed a little to their iOS app. 

I would love to work on a PR with you for this feature. I am primarily an iOS developer but I have never done Android development. I know Java, but I know that desktop Java development is nothing like Android development, so please contact me so we can collaborate on this.  On Telegram, I'm Economic_Hitman

### PR DESCRIPTION
**Pull request by EmilJunker**
I added nutriment subtotals for each category in the diary (should close #218). Tapping the energy total at the bottom of a category now opens a dialog displaying the totals:

Screenshot_20210928-161152

While working on this, I also noticed some issues with the handling of the energy unit setting in the diary. The fixes for that are also included in this PR.

### CODE REVIEW

**Comment by EmilJunker** [comment]
@davidhealey I've resolved the merge conflict for this PR. Are you going to merge this and my other PRs before the next release? From my side they're all ready (except the RTL layout for Hebrew which might need some more work).

**Comment by davidhealey** [comment]
> Are you going to merge this and my other PRs before the next release

I'll review it before the next release and if it's all good I'll merge it.

**Comment by EmilJunker** [comment]
> Looks like we were both thinking the same thing :)

Nevermind :) But in case you were also going to merge the bugfix PR #355, could you wait a few more minutes so I can push one more "cleanup" commit to it?

**Comment by davidhealey** [comment]
> > Looks like we were both thinking the same thing :)
> 
> Nevermind :) But in case you were also going to merge the bugfix PR #355, could you wait a few more minutes so I can push one more "cleanup" commit to it?

Oops, sorry, I was just reviewing that one before I saw your email.

**Comment by davidhealey** [comment]
I can revert it if you like, or you can make a new pull request?

**Comment by EmilJunker** [comment]
Alright, I'll create a new pull request

**Pull request merged**
