### PR TITLE
Add Dutch language labels

### PR DESCRIPTION
**Pull request by lindely**
Add **locale-nl.json** containing app labels translated to Dutch (NL). The new language was added to the **locale** list with identifier **dutch**. 

Only the labels were added; it is up to the developer whether or not to include these in a future update.

### CODE REVIEW

**Comment by EmilJunker** [comment]
@yarons Could you also add Dutch language to the Crowdin project?

**Comment by EmilJunker** [comment]
Just letting you know that I already added Dutch as an option to the language selection menu in anticipation for this addition (see https://github.com/davidhealey/waistline/commit/6274b4dfd357c45e0c28d50956b61bcc5a882646). So it would make sense to merge this PR now.

**Comment by EmilJunker** [comment]
Hey @lindely, you translation is now also on Crowdin: https://crowdin.com/project/waistline/nl

Your translation is currently 93% complete. You can add the missing labels by clicking the link above.

You don't need to create an extra account for Crowdin, you can simply sign in with your github account.

**Comment by lindely** [comment]
@EmilJunker I have added the missing labels. Unsure of the "Camino" one; I added a comment on Crowdin. Will update the word with a better one if necessary after I see it in the app.

**Comment by davidhealey** [comment]
Camino is a Spanish word, it's also a name. It doesn't really need a translation but you can give it one if you want.

**Pull request merged**
