### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by EmilJunker**
Some last-minute improvements, including the changes proposed in #349 and #396.

### CODE REVIEW

**Comment by davidhealey** [comment]
Are you seeing this in the browser console?

image

**Comment by EmilJunker** [comment]
No, I get this when I load the app in the browser (same as always):

image

**Comment by davidhealey** [comment]
Ok, that's good. Just something on my system then :)

**Comment by davidhealey** [comment]
Solved it. Just deleted platforms and plugins and readded the platforms.

**Comment by EmilJunker** [comment]
Good. Did it fetch cordova-android 9x or 10x when you added the platform?

**Comment by davidhealey** [comment]
I had to force it with android@10

**Pull request merged**
